services:
  postgres:
    image: postgres:17.5-alpine
    environment:
      POSTGRES_DB: ranking_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d ranking_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: